# Pull gems from RubyGems
source 'https://rubygems.org'

gem 'sass',					"~> 3.4.0.rc.3"
gem 'compass',            	"~>1.0.0.rc.1"
gem 'breakpoint',         	"~> 2.4"
gem 'singularitygs', 		"~>1.1.2"
